sudo: false
language: go

go:
  - 1.9.x
  - 1.8.x

addons:
  apt:
    packages:
      - oracle-java8-set-default

env:
  - SCALA_VERSION=2.11 KAFKA_VERSION=0.10.1.1
  - SCALA_VERSION=2.12 KAFKA_VERSION=0.11.0.1
  - SCALA_VERSION=2.12 KAFKA_VERSION=1.0.0

install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure

script:
  - make vet test-race APACHE_MIRROR=https://archive.apache.org/dist

branches:
  only:
  - master

notifications:
  email: false
